name: Slimefun
version: 2.3
author: mrCookieSlime
website: http://dev.bukkit.org/profiles/mrCookieSlime/bukkit-plugins/

main: me.mrCookieSlime.Slimefun.startup

commands:
  milk:
       description: Removes all PotionEffects
       usage: /milk <Player>
  slimefun:
       description: Shows the Slimefun commands
       usage: /slimefun <argument>
  sf:
       description: Alias for /slimefun
       usage: /sf <argument>
permissions:
  slimefun.milk.*:
       description: Let's you remove Potion Effects from all people
       default: op
       children:
         slimefun.milk.self: true
         slimefun.milk.other: true
  slimefun.milk.self:
       description: Let's you remove Potion Effects from you
       default: true
  slimefun.milk.other:
       description: Let's you remove Potion Effects from other people
       default: op
  slimefun.port:
       description: Can port to another Player
       default: op
  slimefun.reload:
       description: Reloads the config file
       default: op
  slimefun.itome:
       description: Gives access to the Invisibility Tome
       default: op
  slimefun.tomeofhomeland:
       description: Gives access to the Tome of Homeland
       default: op
  slimefun.items:
       description: Gives access to /sf items
       default: op
  slimefun.craft.itome:
       description: Allows you to craft the iTome
       default: op
  slimefun.craft.BookoTeleporting:
       description: Allows you to craft the Book o' Teleporting
       default: op
  slimefun.craft.tomeofhomeland:
       description: Allows you to craft the Tome of homeland
       default: true
  slimefun.jetpack:
       description: Allows you to use the Jetpack
       default: op
  slimefun.parachute:
       description: Allows you to use the parachute
       default: op
  slimefun.iTome.see-players:
       description: Allows you to see vanished Players
       default: op
  slimefun.killnpc:
       description: Allows you to remove Slimefun Villagers
       default: op
  slimefun.cheat.research:
       description: Allows to cheat Researches
       default: op