package me.mrCookieSlime.Slimefun.Setup;

import me.mrCookieSlime.Slimefun.AddonHandler.Slimefun;
import me.mrCookieSlime.Slimefun.Items.SlimefunItem;

public class Researches {
	
	public static void setup() {
		
		Slimefun.addResearch("Walking sticks");
		Slimefun.addResearch("Portable Crafter");
		Slimefun.addResearch("Super Meat");
		Slimefun.addResearch("Fortune Cookie");
		Slimefun.addResearch("Portable Enchanter");
		Slimefun.addResearch("Portable Dustbin");
		Slimefun.addResearch("Armor Crafting");
		Slimefun.addResearch("Glowstone armor");
		Slimefun.addResearch("Lumps and Magic");
		Slimefun.addResearch("Ender Backpack");
		Slimefun.addResearch("Magic Eye of Ender");
		Slimefun.addResearch("Ender armor");
		Slimefun.addResearch("Partially Golden Apple");
		Slimefun.addResearch("Magic Sugar");
		Slimefun.addResearch("Uber Meat");
		Slimefun.addResearch("Slime armor");
		Slimefun.addResearch("Sword of Beheading");
		Slimefun.addResearch("Portable Tool Bench");
		Slimefun.addResearch("Portable Book Binder");
		Slimefun.addResearch("Portable Jukebox");
		Slimefun.addResearch("Tome of Homeland");
		Slimefun.addResearch("Invisible Tome");
		Slimefun.addResearch("Book o Teleporting");
		Slimefun.addResearch("Electric Work");
		Slimefun.addResearch("Advanced Circuit Board");
		Slimefun.addResearch("Ore Washing");
		Slimefun.addResearch("Hot Melting");
		Slimefun.addResearch("Steel Ingot");
		Slimefun.addResearch("Battery");
		Slimefun.addResearch("Water Mill");
		Slimefun.addResearch("Electric Furnace");
		Slimefun.addResearch("Miners Compass");
		Slimefun.addResearch("Steel Thruster");
		Slimefun.addResearch("Steel Plate");
		Slimefun.addResearch("Parachute");
		Slimefun.addResearch("Chain");
		Slimefun.addResearch("Hook");
		Slimefun.addResearch("Grappling Hook");
		Slimefun.addResearch("Jetpack");
		Slimefun.addResearch("Multi Tool");
		Slimefun.addResearch("Refueling Station");
		Slimefun.addResearch("Solar Panel");
		Slimefun.addResearch("Emerald of Repairing");
		Slimefun.addResearch("Crystal of Repairing");
		Slimefun.addResearch("Ender Crystal of Repairing");
		Slimefun.addResearch("Golden Feather");
		Slimefun.addResearch("Diamond of Duplicating");
		Slimefun.addResearch("Portable Hole");
		Slimefun.addResearch("Thermal Generator");
		Slimefun.addResearch("Nano Tools");
		Slimefun.addResearch("Nano Pickaxe");
		Slimefun.addResearch("Nano Axel");
		Slimefun.addResearch("Nano Saber");
		Slimefun.addResearch("Nano armor");
		Slimefun.addResearch("Quantum armor");
		Slimefun.addResearch("Amulet of Revival");
		Slimefun.addResearch("Uber armor");
		Slimefun.addResearch("Uber Upgrade Cores");
		Slimefun.addResearch("Uber Axe");
		Slimefun.addResearch("Uber Pickaxe");
		
		Slimefun.registerResearch(SlimefunItem.GRANDMAS_WALKING_STICK, "Walking sticks");
		Slimefun.registerResearch(SlimefunItem.GRANDPAS_WALKING_STICK, "Walking sticks");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_CRAFTER, "Portable Crafter");
		Slimefun.registerResearch(SlimefunItem.SUPER_MEAT, "Super Meat");
		Slimefun.registerResearch(SlimefunItem.FORTUNE_COOKIE, "Fortune Cookie");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_ENCHANTER, "Portable Enchanter");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_DUSTBIN, "Portable Dustbin");
		Slimefun.registerResearch(SlimefunItem.TOOL_BENCH, "Armor Crafting");
		Slimefun.registerResearch(SlimefunItem.GLOWSTONE_HELMET, "Glowstone armor");
		Slimefun.registerResearch(SlimefunItem.GLOWSTONE_CHESTPLATE, "Glowstone armor");
		Slimefun.registerResearch(SlimefunItem.GLOWSTONE_LEGGINGS, "Glowstone armor");
		Slimefun.registerResearch(SlimefunItem.GLOWSTONE_BOOTS, "Glowstone armor");
		Slimefun.registerResearch(SlimefunItem.ENDER_BACKPACK, "Ender Backpack");
		Slimefun.registerResearch(SlimefunItem.MAGIC_EYE_OF_ENDER, "Magic Eye of Ender");
		Slimefun.registerResearch(SlimefunItem.ENDER_HELMET, "Ender armor");
		Slimefun.registerResearch(SlimefunItem.ENDER_CHESTPLATE, "Ender armor");
		Slimefun.registerResearch(SlimefunItem.ENDER_LEGGINGS, "Ender armor");
		Slimefun.registerResearch(SlimefunItem.ENDER_BOOTS, "Ender armor");
		Slimefun.registerResearch(SlimefunItem.PARTIALLY_GOLDEN_APPLE, "Partially Golden Apple");
		Slimefun.registerResearch(SlimefunItem.MAGIC_SUGAR, "Magic Sugar");
		Slimefun.registerResearch(SlimefunItem.UBER_MEAT, "Uber Meat");
		Slimefun.registerResearch(SlimefunItem.SLIME_HELMET, "Slime armor");
		Slimefun.registerResearch(SlimefunItem.SLIME_CHESTPLATE, "Slime armor");
		Slimefun.registerResearch(SlimefunItem.SLIME_LEGGINGS, "Slime armor");
		Slimefun.registerResearch(SlimefunItem.SLIME_BOOTS, "Slime armor");
		Slimefun.registerResearch(SlimefunItem.SWORD_OF_BEHEADING, "Sword of Beheading");
		Slimefun.registerResearch(SlimefunItem.MAGICAL_LUMP_1, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.MAGICAL_LUMP_2, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.MAGICAL_LUMP_3, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.ENDER_LUMP_1, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.ENDER_LUMP_2, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.ENDER_LUMP_3, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_BOOK_BINDER, "Portable Book Binder");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_TOOL_BENCH, "Portable Tool Bench");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_JUKEBOX, "Portable Jukebox");
		Slimefun.registerResearch(SlimefunItem.TOME_OF_HOMELAND, "Tome of Homeland");
		Slimefun.registerResearch(SlimefunItem.INVISIBLE_TOME, "Invisible Tome");
		Slimefun.registerResearch(SlimefunItem.BOOK_O_TELEPORTING, "Book o Teleporting");
		Slimefun.registerResearch(SlimefunItem.SIMPLE_CIRCUIT_BOARD, "Electric Work");
		Slimefun.registerResearch(SlimefunItem.ADVANCED_CIRCUIT_BOARD, "Advanced Circuit Board");
		Slimefun.registerResearch(SlimefunItem.SMELTERY, "Hot Melting");
		Slimefun.registerResearch(SlimefunItem.STEEL_INGOT, "Steel Ingot");
		Slimefun.registerResearch(SlimefunItem.STEEL_THRUSTER, "Steel Thruster");
		Slimefun.registerResearch(SlimefunItem.STEEL_PLATE, "Steel Plate");
		Slimefun.registerResearch(SlimefunItem.PARACHUTE, "Parachute");
		Slimefun.registerResearch(SlimefunItem.CHAIN, "Chain");
		Slimefun.registerResearch(SlimefunItem.HOOK, "Hook");
		Slimefun.registerResearch(SlimefunItem.GRAPPLING_HOOK, "Grappling Hook");
		Slimefun.registerResearch(SlimefunItem.JETPACK, "Jetpack");
		Slimefun.registerResearch(SlimefunItem.MULTI_TOOL_MODE_NONE, "Multi Tool");
		Slimefun.registerResearch(SlimefunItem.EMERALD_OF_REPAIRING, "Emerald of Repairing");
		Slimefun.registerResearch(SlimefunItem.CRYSTAL_OF_REPAIRING, "Crystal of Repairing");
		Slimefun.registerResearch(SlimefunItem.ENDER_CRYSTAL_OF_REPAIRING, "Ender Crystal of Repairing");
		Slimefun.registerResearch(SlimefunItem.DIAMOND_OF_DUPLICATING, "Diamond of Duplicating");
		Slimefun.registerResearch(SlimefunItem.NANO_FOCUS, "Nano Tools");
		Slimefun.registerResearch(SlimefunItem.NANO_HOE, "Nano Tools");
		Slimefun.registerResearch(SlimefunItem.NANO_PICKAXE, "Nano Pickaxe");
		Slimefun.registerResearch(SlimefunItem.NANO_AXEL, "Nano Axel");
		Slimefun.registerResearch(SlimefunItem.NANO_SABER, "Nano Saber");
		Slimefun.registerResearch(SlimefunItem.NANO_HELMET, "Nano armor");
		Slimefun.registerResearch(SlimefunItem.NANO_CHESTPLATE, "Nano armor");
		Slimefun.registerResearch(SlimefunItem.NANO_LEGGINGS, "Nano armor");
		Slimefun.registerResearch(SlimefunItem.NANO_BOOTS, "Nano armor");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_HELMET, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_CHESTPLATE, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_LEGGINGS, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_BOOTS, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.UBER_HELMET, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.UBER_CHESTPLATE, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.UBER_LEGGINGS, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.UBER_BOOTS, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.MINERS_COMPASS, "Miners Compass");
		Slimefun.registerResearch(SlimefunItem.ORE_WASHER, "Ore Washing");
		Slimefun.registerResearch(SlimefunItem.IRON_CHUNK, "Ore Washing");
		Slimefun.registerResearch(SlimefunItem.GOLD_CHUNK, "Ore Washing");
		Slimefun.registerResearch(SlimefunItem.GOLDEN_FEATHER, "Golden Feather");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_HOLE, "Portable Hole");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_FOCUS, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.UBER_FOCUS, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.UBER_AXE, "Uber Axe");
		Slimefun.registerResearch(SlimefunItem.AMULET_OF_REVIVAL, "Amulet of Revival");
		Slimefun.registerResearch(SlimefunItem.UBER_PICKAXE, "Uber Pickaxe");
		Slimefun.registerResearch(SlimefunItem.BATTERY, "Battery");
		Slimefun.registerResearch(SlimefunItem.WATER_MILL, "Water Mill");
		Slimefun.registerResearch(SlimefunItem.SOLAR_PANEL, "Solar Panel");
		Slimefun.registerResearch(SlimefunItem.THERMAL_GENERATOR, "Thermal Generator");
		Slimefun.registerResearch(SlimefunItem.ELECTRIC_FURNACE, "Electric Furnace");
		Slimefun.registerResearch(SlimefunItem.REFUELING_STATION, "Refueling Station");
		
		Slimefun.registerDigitalName(SlimefunItem.NANO_PICKAXE,"nanopickaxe");
		Slimefun.registerDigitalName(SlimefunItem.PORTABLE_DUSTBIN, "dustbin");
		Slimefun.registerDigitalName(SlimefunItem.ENDER_BACKPACK, "enderbackpack");
		Slimefun.registerDigitalName(SlimefunItem.GRANDPAS_WALKING_STICK, "grandpaswalkingstick");
		Slimefun.registerDigitalName(SlimefunItem.GRANDMAS_WALKING_STICK, "grandmaswalkingstick");
		Slimefun.registerDigitalName(SlimefunItem.SUPER_MEAT, "supermeat");
		Slimefun.registerDigitalName(SlimefunItem.NANO_HOE, "nanohoe");
		Slimefun.registerDigitalName(SlimefunItem.NANO_SABER, "nanosaber");
		Slimefun.registerDigitalName(SlimefunItem.TOOL_BENCH, "toolbench");
		Slimefun.registerDigitalName(SlimefunItem.SIMPLE_CIRCUIT_BOARD, "simplecircuitboard");
		Slimefun.registerDigitalName(SlimefunItem.INVISIBLE_TOME, "itome");
		Slimefun.registerDigitalName(SlimefunItem.BOOK_O_TELEPORTING, "bookoteleporting");
		Slimefun.registerDigitalName(SlimefunItem.PORTABLE_ENCHANTER, "penchanter");
		Slimefun.registerDigitalName(SlimefunItem.PORTABLE_CRAFTER, "pcrafter");
		Slimefun.registerDigitalName(SlimefunItem.TOME_OF_HOMELAND, "tomeofhomeland");
		Slimefun.registerDigitalName(SlimefunItem.PORTABLE_TOOL_BENCH, "ptoolbench");
		Slimefun.registerDigitalName(SlimefunItem.PORTABLE_BOOK_BINDER, "pbookbinder");
		Slimefun.registerDigitalName(SlimefunItem.STEEL_INGOT, "steelingot");
		Slimefun.registerDigitalName(SlimefunItem.ADVANCED_CIRCUIT_BOARD, "advancedcircuitboard");
		Slimefun.registerDigitalName(SlimefunItem.STEEL_THRUSTER, "steelthruster");
		Slimefun.registerDigitalName(SlimefunItem.JETPACK, "jetpack");
		Slimefun.registerDigitalName(SlimefunItem.PORTABLE_JUKEBOX, "pjukebox");
		Slimefun.registerDigitalName(SlimefunItem.NANO_AXEL, "nanoaxel");
		Slimefun.registerDigitalName(SlimefunItem.MAGIC_EYE_OF_ENDER, "magiceyeofender");
		Slimefun.registerDigitalName(SlimefunItem.PARACHUTE, "parachute");
		Slimefun.registerDigitalName(SlimefunItem.UBER_MEAT, "ubermeat");
		Slimefun.registerDigitalName(SlimefunItem.PARTIALLY_GOLDEN_APPLE, "partiallygoldenapple");
		Slimefun.registerDigitalName(SlimefunItem.MAGIC_SUGAR, "magicsugar");
		Slimefun.registerDigitalName(SlimefunItem.MAGICAL_LUMP_1, "magicallump1");
		Slimefun.registerDigitalName(SlimefunItem.MAGICAL_LUMP_2, "magicallump2");
		Slimefun.registerDigitalName(SlimefunItem.MAGICAL_LUMP_3, "magicallump3");
		Slimefun.registerDigitalName(SlimefunItem.ENDER_LUMP_1, "enderlump1");
		Slimefun.registerDigitalName(SlimefunItem.ENDER_LUMP_2, "enderlump2");
		Slimefun.registerDigitalName(SlimefunItem.ENDER_LUMP_3, "enderlump3");
		Slimefun.registerDigitalName(SlimefunItem.CRYSTAL_OF_REPAIRING, "crystalofrepairing");
		Slimefun.registerDigitalName(SlimefunItem.ENDER_CRYSTAL_OF_REPAIRING, "endercrystalofrepairing");
		Slimefun.registerDigitalName(SlimefunItem.SLIMEFUN_GUIDE, "guide");
		Slimefun.registerDigitalName(SlimefunItem.SWORD_OF_BEHEADING, "swordofbeheading");
		Slimefun.registerDigitalName(SlimefunItem.EMERALD_OF_REPAIRING, "emeraldofrepairing");
		Slimefun.registerDigitalName(SlimefunItem.MULTI_TOOL_MODE_NONE, "multitool");
		Slimefun.registerDigitalName(SlimefunItem.STEEL_PLATE, "steelplate");
		Slimefun.registerDigitalName(SlimefunItem.CHAIN, "chain");
		Slimefun.registerDigitalName(SlimefunItem.FORTUNE_COOKIE, "fortunecookie");
		Slimefun.registerDigitalName(SlimefunItem.GRAPPLING_HOOK, "grapplinghook");
		Slimefun.registerDigitalName(SlimefunItem.HOOK, "hook");
		Slimefun.registerDigitalName(SlimefunItem.DIAMOND_OF_DUPLICATING, "diamondofduplicating");
		Slimefun.registerDigitalName(SlimefunItem.SLIME_GEM, "slimegem");
		Slimefun.registerDigitalName(SlimefunItem.INK_OF_KNOWLEDGE, "inkofknowledge");
		Slimefun.registerDigitalName(SlimefunItem.MINERS_COMPASS, "minerscompass");
		Slimefun.registerDigitalName(SlimefunItem.NANO_FOCUS, "nanofocus");
		Slimefun.registerDigitalName(SlimefunItem.QUANTUM_FOCUS, "quantumfocus");
		Slimefun.registerDigitalName(SlimefunItem.UBER_FOCUS, "uberfocus");
		Slimefun.registerDigitalName(SlimefunItem.IRON_CHUNK, "ironchunk");
		Slimefun.registerDigitalName(SlimefunItem.GOLD_CHUNK, "goldchunk");
		Slimefun.registerDigitalName(SlimefunItem.GOLDEN_FEATHER, "goldenfeather");
		Slimefun.registerDigitalName(SlimefunItem.PORTABLE_HOLE, "portablehole");
		Slimefun.registerDigitalName(SlimefunItem.UBER_AXE, "uberaxe");
		Slimefun.registerDigitalName(SlimefunItem.AMULET_OF_REVIVAL, "amuletofrevival");
		Slimefun.registerDigitalName(SlimefunItem.UBER_PICKAXE, "uberpickaxe");
		Slimefun.registerDigitalName(SlimefunItem.BATTERY, "battery");
	}

}
