package me.mrCookieSlime.Slimefun.Setup;

import me.mrCookieSlime.Slimefun.AddonHandler.Slimefun;
import me.mrCookieSlime.Slimefun.Items.SlimefunItem;

public class Researches {
	
	public static void setup() {
		
		Slimefun.addResearch("Walking sticks");
		Slimefun.addResearch("Portable Crafter");
		Slimefun.addResearch("Super Meat");
		Slimefun.addResearch("Fortune Cookie");
		Slimefun.addResearch("Portable Enchanter");
		Slimefun.addResearch("Portable Dustbin");
		Slimefun.addResearch("Armor Crafting");
		Slimefun.addResearch("Glowstone armor");
		Slimefun.addResearch("Lumps and Magic");
		Slimefun.addResearch("Ender Backpack");
		Slimefun.addResearch("Magic Eye of Ender");
		Slimefun.addResearch("Ender armor");
		Slimefun.addResearch("Partially Golden Apple");
		Slimefun.addResearch("Magic Sugar");
		Slimefun.addResearch("Uber Meat");
		Slimefun.addResearch("Slime armor");
		Slimefun.addResearch("Sword of Beheading");
		Slimefun.addResearch("Portable Tool Bench");
		Slimefun.addResearch("Portable Book Binder");
		Slimefun.addResearch("Portable Jukebox");
		Slimefun.addResearch("Tome of Homeland");
		Slimefun.addResearch("Invisible Tome");
		Slimefun.addResearch("Book o Teleporting");
		Slimefun.addResearch("Electric Work");
		Slimefun.addResearch("Advanced Circuit Board");
		Slimefun.addResearch("Ore Washing");
		Slimefun.addResearch("Hot Melting");
		Slimefun.addResearch("Steel Ingot");
		Slimefun.addResearch("Miners Compass");
		Slimefun.addResearch("Steel Thruster");
		Slimefun.addResearch("Steel Plate");
		Slimefun.addResearch("Parachute");
		Slimefun.addResearch("Chain");
		Slimefun.addResearch("Hook");
		Slimefun.addResearch("Grappling Hook");
		Slimefun.addResearch("Jetpack");
		Slimefun.addResearch("Multi Tool");
		Slimefun.addResearch("Emerald of Repairing");
		Slimefun.addResearch("Crystal of Repairing");
		Slimefun.addResearch("Ender Crystal of Repairing");
		Slimefun.addResearch("Golden Feather");
		Slimefun.addResearch("Diamond of Duplicating");
		Slimefun.addResearch("Portable Hole");
		Slimefun.addResearch("Nano Tools");
		Slimefun.addResearch("Nano Pickaxe");
		Slimefun.addResearch("Nano Axel");
		Slimefun.addResearch("Nano Saber");
		Slimefun.addResearch("Nano armor");
		Slimefun.addResearch("Quantum armor");
		Slimefun.addResearch("Uber armor");
		Slimefun.addResearch("Uber Upgrade Cores");
		Slimefun.addResearch("Uber Axe");
		
		Slimefun.registerResearch(SlimefunItem.GRANDMAS_WALKING_STICK, "Walking sticks");
		Slimefun.registerResearch(SlimefunItem.GRANDPAS_WALKING_STICK, "Walking sticks");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_CRAFTER, "Portable Crafter");
		Slimefun.registerResearch(SlimefunItem.SUPER_MEAT, "Super Meat");
		Slimefun.registerResearch(SlimefunItem.FORTUNE_COOKIE, "Fortune Cookie");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_ENCHANTER, "Portable Enchanter");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_DUSTBIN, "Portable Dustbin");
		Slimefun.registerResearch(SlimefunItem.TOOL_BENCH, "Armor Crafting");
		Slimefun.registerResearch(SlimefunItem.GLOWSTONE_HELMET, "Glowstone armor");
		Slimefun.registerResearch(SlimefunItem.GLOWSTONE_CHESTPLATE, "Glowstone armor");
		Slimefun.registerResearch(SlimefunItem.GLOWSTONE_LEGGINGS, "Glowstone armor");
		Slimefun.registerResearch(SlimefunItem.GLOWSTONE_BOOTS, "Glowstone armor");
		Slimefun.registerResearch(SlimefunItem.ENDER_BACKPACK, "Ender Backpack");
		Slimefun.registerResearch(SlimefunItem.MAGIC_EYE_OF_ENDER, "Magic Eye of Ender");
		Slimefun.registerResearch(SlimefunItem.ENDER_HELMET, "Ender armor");
		Slimefun.registerResearch(SlimefunItem.ENDER_CHESTPLATE, "Ender armor");
		Slimefun.registerResearch(SlimefunItem.ENDER_LEGGINGS, "Ender armor");
		Slimefun.registerResearch(SlimefunItem.ENDER_BOOTS, "Ender armor");
		Slimefun.registerResearch(SlimefunItem.PARTIALLY_GOLDEN_APPLE, "Partially Golden Apple");
		Slimefun.registerResearch(SlimefunItem.MAGIC_SUGAR, "Magic Sugar");
		Slimefun.registerResearch(SlimefunItem.UBER_MEAT, "Uber Meat");
		Slimefun.registerResearch(SlimefunItem.SLIME_HELMET, "Slime armor");
		Slimefun.registerResearch(SlimefunItem.SLIME_CHESTPLATE, "Slime armor");
		Slimefun.registerResearch(SlimefunItem.SLIME_LEGGINGS, "Slime armor");
		Slimefun.registerResearch(SlimefunItem.SLIME_BOOTS, "Slime armor");
		Slimefun.registerResearch(SlimefunItem.SWORD_OF_BEHEADING, "Sword of Beheading");
		Slimefun.registerResearch(SlimefunItem.MAGICAL_LUMP_1, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.MAGICAL_LUMP_2, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.MAGICAL_LUMP_3, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.ENDER_LUMP_1, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.ENDER_LUMP_2, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.ENDER_LUMP_3, "Lumps and Magic");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_BOOK_BINDER, "Portable Book Binder");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_TOOL_BENCH, "Portable Tool Bench");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_JUKEBOX, "Portable Jukebox");
		Slimefun.registerResearch(SlimefunItem.TOME_OF_HOMELAND, "Tome of Homeland");
		Slimefun.registerResearch(SlimefunItem.INVISIBLE_TOME, "Invisible Tome");
		Slimefun.registerResearch(SlimefunItem.BOOK_O_TELEPORTING, "Book o Teleporting");
		Slimefun.registerResearch(SlimefunItem.SIMPLE_CIRCUIT_BOARD, "Electric Work");
		Slimefun.registerResearch(SlimefunItem.ADVANCED_CIRCUIT_BOARD, "Advanced Circuit Board");
		Slimefun.registerResearch(SlimefunItem.SMELTERY, "Hot Melting");
		Slimefun.registerResearch(SlimefunItem.STEEL_INGOT, "Steel Ingot");
		Slimefun.registerResearch(SlimefunItem.STEEL_THRUSTER, "Steel Thruster");
		Slimefun.registerResearch(SlimefunItem.STEEL_PLATE, "Steel Plate");
		Slimefun.registerResearch(SlimefunItem.PARACHUTE, "Parachute");
		Slimefun.registerResearch(SlimefunItem.CHAIN, "Chain");
		Slimefun.registerResearch(SlimefunItem.HOOK, "Hook");
		Slimefun.registerResearch(SlimefunItem.GRAPPLING_HOOK, "Grappling Hook");
		Slimefun.registerResearch(SlimefunItem.JETPACK, "Jetpack");
		Slimefun.registerResearch(SlimefunItem.MULTI_TOOL_MODE_NONE, "Multi Tool");
		Slimefun.registerResearch(SlimefunItem.EMERALD_OF_REPAIRING, "Emerald of Repairing");
		Slimefun.registerResearch(SlimefunItem.CRYSTAL_OF_REPAIRING, "Crystal of Repairing");
		Slimefun.registerResearch(SlimefunItem.ENDER_CRYSTAL_OF_REPAIRING, "Ender Crystal of Repairing");
		Slimefun.registerResearch(SlimefunItem.DIAMOND_OF_DUPLICATING, "Diamond of Duplicating");
		Slimefun.registerResearch(SlimefunItem.NANO_FOCUS, "Nano Tools");
		Slimefun.registerResearch(SlimefunItem.NANO_HOE, "Nano Tools");
		Slimefun.registerResearch(SlimefunItem.NANO_PICKAXE, "Nano Pickaxe");
		Slimefun.registerResearch(SlimefunItem.NANO_AXEL, "Nano Axel");
		Slimefun.registerResearch(SlimefunItem.NANO_SABER, "Nano Saber");
		Slimefun.registerResearch(SlimefunItem.NANO_HELMET, "Nano armor");
		Slimefun.registerResearch(SlimefunItem.NANO_CHESTPLATE, "Nano armor");
		Slimefun.registerResearch(SlimefunItem.NANO_LEGGINGS, "Nano armor");
		Slimefun.registerResearch(SlimefunItem.NANO_BOOTS, "Nano armor");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_HELMET, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_CHESTPLATE, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_LEGGINGS, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_BOOTS, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.UBER_HELMET, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.UBER_CHESTPLATE, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.UBER_LEGGINGS, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.UBER_BOOTS, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.MINERS_COMPASS, "Miners Compass");
		Slimefun.registerResearch(SlimefunItem.ORE_WASHER, "Ore Washing");
		Slimefun.registerResearch(SlimefunItem.IRON_CHUNK, "Ore Washing");
		Slimefun.registerResearch(SlimefunItem.GOLD_CHUNK, "Ore Washing");
		Slimefun.registerResearch(SlimefunItem.GOLDEN_FEATHER, "Golden Feather");
		Slimefun.registerResearch(SlimefunItem.PORTABLE_HOLE, "Portable Hole");
		Slimefun.registerResearch(SlimefunItem.QUANTUM_FOCUS, "Quantum armor");
		Slimefun.registerResearch(SlimefunItem.UBER_FOCUS, "Uber armor");
		Slimefun.registerResearch(SlimefunItem.UBER_AXE, "Uber Axe");
	}

}
